# Generated by Django 3.2.13 on 2022-05-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='birth_day',
        ),
    ]
