# Generated by Django 3.2.13 on 2022-05-30 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_loginuser_birth_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='gender',
        ),
    ]
